name: notebook
channels:
  - eoas_ubc
  - conda-forge
dependencies:
  - dash
  - plotly
  - python < 3.10.0
  - gunicorn
  - flask
  - pip
  - pandas
  - scikit-image
  - conda-lock
  - scipy
  - pooch
  - cftime
  - xarray
  - pandas
  - fsspec
  - zarr
# conda-lock -f environment.yml -p linux-64
