#Traefik Global Configuration
debug = false
checkNewVersion = false
logLevel = "ERROR"

#Define the EntryPoint for HTTP and HTTPS
defaultEntryPoints = ["https","http"]

#Enable Traefik Dashboard on port 8080
#with basic authentication method
#phil and doitnow
<<<<<<< HEAD
[web]
address = ":8080"
[web.auth.basic]
users = ["phil:$apr1$T1qLNvVo$jVm15GW/mDPSa/nzxCil/1"]
=======
[api]
entrypoint="web"
>>>>>>> working with nbgrader.eoastest2.xyz/trythis

#Define the HTTP port 80 and
#HTTPS port 443 EntryPoint
#Enable automatically redirect HTTP to HTTPS
[entryPoints]
[entryPoints.http]
address = ":80"
[entryPoints.http.redirect]
entryPoint = "https"
[entryPoints.https]
address = ":443"
[entryPoints.https.tls]

<<<<<<< HEAD
=======
[entryPoints.web]
address = ":8080"
[entryPoints.web.aut]
[entryPoints.web.auth.basic]
users = ["phil:$apr1$T1qLNvVo$jVm15GW/mDPSa/nzxCil/1"]


>>>>>>> working with nbgrader.eoastest2.xyz/trythis
#Enable retry sending a request if the network error
[retry]

#Define Docker Backend Configuration
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "eoastest2.xyz"
watch = true
exposedbydefault = false

#Letsencrypt Registration
#Define the Letsencrypt ACME HTTP challenge
[acme]
email = "paustin@eoas.ubc.ca"
storage = "/etc/traefik/acme.json"
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
entryPoint = "https"
OnHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"

[file]
  directory = "/etc/traefik"
  watch = true
  